version: '3.1'

services:
  db:
    build: ./db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 6080:8080
    # environment:
    #   - PMA_ARBITRARY=1